name: Build

on: [workflow_dispatch]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update build environment
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libcups2-dev libcupsimage2-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev libusb-1.0-0-dev zlib1g-dev
    - name: install PAPPL
      run: git clone https://github.com/michaelrsweet/pappl.git && cd pappl && ./configure --enable-debug && make && sudo make install
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer
    - name: ls
      run: ls
    - name: zip
      run: zip -r foo.zip .
    - name: upload
      run: curl --upload-file ./foo.zip https://transfer.sh/foo.zip
